refactor: Enhance validation, exception handling, and entity management
DmitryFedoroff/java-filmorate pull request #2
Opened 2024-08-16 09:05 UTC by DmitryFedoroff

#comment Refactor application to improve data validation, exception handling, and management of User and Film entities:

1. Introduce custom annotations and validators (NoSpacesValidator, DateAfterStandart) to enforce specific validation rules, such as preventing spaces in usernames and restricting film release dates.
2. Implement global exception handling via GlobalExceptionHandler to provide consistent and informative error responses across the application.
3. Manage User and Film entities through newly created controllers (UserController, FilmController) with comprehensive CRUD operations, including validation checks and error management.
4. Add custom exceptions (NotFoundException, DuplicatedDataException, ValidationException) to handle specific error scenarios such as resource not found, data duplication, and validation failures.
5. Integrate utility class BaseEntityUtils to manage unique ID generation for in-memory storage of entities.
6. Modify Film and User models to include necessary fields and validation constraints, ensuring data integrity.
7. Update pom.xml to include spring-boot-starter-validation dependency, enabling the use of validation annotations.
8. Create comprehensive unit tests (UserValidationTest, FilmValidationTest) to validate the behavior of User and Film entities under various conditions.
9. Adjust application properties to set the server port and other relevant configurations.

Affected: GlobalExceptionHandler, NoSpacesValidator, NoSpacesValidatorImpl, ValidationException, NotFoundException, DuplicatedDataException, DateAfterStandart, DateAfterStandartValidator, UserController, FilmController, BaseEntityUtils, User, Film, pom.xml, application.properties, UserValidationTest, FilmValidationTest

2024-08-16 15:57 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-08-16 15:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/annotation/DateAfterStandartValidator.java
> +        return !localDate.isBefore(standartDate);
можно использовать тернарный оператор

2024-08-16 15:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final LocalDate minReleaseDate = LocalDate.of(1895, 12, 28);
А зачем нам это поле и проверка, если мы хотим использовать валидацию с помощью аннотации `DateAfterStandart`?

2024-08-16 15:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (existingFilm == null) {
Вместо проверки на `null`, лучше использовать стандартный метод `containsKey`

2024-08-16 15:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private boolean isUserWithEmailExist(String eMail) {
Этот метод работает за `O(n)`, где `n` -- количество элементов в коллекции.  Его можно реализовать эффективнее, попробуй сделать это. Возможно, тебе понадобится дополнительная коллекция

2024-08-16 15:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/util/BaseEntityUtils.java
> +public class BaseEntityUtils {
Этот класс стоит оформить, как класс-помощник или `@UtilityClass`:

https://www.baeldung.com/java-helper-vs-utility-classes

2024-08-16 15:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/validator/NoSpacesValidatorImpl.java
> +        return !value.contains(" ");
можно использовать тернарный оператор

2024-08-16 15:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/validator/NoSpacesValidatorImpl.java
> +public class NoSpacesValidatorImpl implements ConstraintValidator<NoSpacesValidator, String> {
Можно воспользоваться существующей аннотацией:

```
@Pattern(regexp = "[\\S]+")
```

2024-08-17 11:31 UTC, DmitryFedoroff commented on src/main/java/ru/yandex/practicum/filmorate/validator/NoSpacesValidatorImpl.java
> +public class NoSpacesValidatorImpl implements ConstraintValidator<NoSpacesValidator, String> {
**Исправлено**: Заменена кастомная аннотация `@NoSpacesValidator` на стандартную аннотацию `@Pattern(regexp = "\\S+")` для поля `login` в классе `User`.

2024-08-17 11:32 UTC, DmitryFedoroff commented on src/main/java/ru/yandex/practicum/filmorate/validator/NoSpacesValidatorImpl.java
> +        return !value.contains(" ");
**Удалено**: Класс `NoSpacesValidatorImpl`, так как он стал ненужным из-за замены его логики аннотацией `@Pattern` в классе `User`.

2024-08-17 11:34 UTC, DmitryFedoroff commented on src/main/java/ru/yandex/practicum/filmorate/util/BaseEntityUtils.java
> +public class BaseEntityUtils {
**Исправлено**: Класс `BaseEntityUtils` оформлен как Utility-класс с использованием аннотации `@UtilityClass`.

2024-08-17 11:35 UTC, DmitryFedoroff commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private boolean isUserWithEmailExist(String eMail) {
**Исправлено**: Оптимизирован метод `isUserWithEmailExist()` с использованием `Set<String>` для хранения email-адресов, что ускоряет проверку наличия email до `O(1)`.

2024-08-17 11:37 UTC, DmitryFedoroff commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (existingFilm == null) {
**Исправлено**: Заменена проверка на `null` методом `containsKey()` в методе `update()`.

2024-08-17 11:37 UTC, DmitryFedoroff commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final LocalDate minReleaseDate = LocalDate.of(1895, 12, 28);
**Исправлено**: Удалено поле `minReleaseDate` и соответствующая проверка в классе `FilmController`. Валидация даты релиза теперь полностью выполняется с помощью аннотации `@DateAfterStandart`.

2024-08-17 11:38 UTC, DmitryFedoroff commented on src/main/java/ru/yandex/practicum/filmorate/annotation/DateAfterStandartValidator.java
> +        return !localDate.isBefore(standartDate);
**Исправлено**: Использован тернарный оператор для проверки на `null` в методе `isValid()`.

2024-08-18 18:37 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-08-19 01:52 UTC, DmitryFedoroff commented
#comment Refactor existing classes and introduce new functionality for improved validation, error handling, and user management:

1. Update pom.xml to include the spring-boot-starter-validation dependency.
2. Modify Film class by adding validation annotations like @NotBlank, @Size, and custom annotation @DateAfterStandart to enforce field constraints.
3. Enhance FilmController by updating create and update methods to incorporate new validation logic and logging improvements.
4. Introduce custom exceptions: NotFoundException, DuplicatedDataException, and ValidationException for handling specific error scenarios.
5. Add BaseEntityUtils class for common entity operations like ID generation.
6. Create User class with validation annotations for fields like email, login, and birthday.
7. Implement UserController for managing user operations, including create, update, and fetch users.
8. Add UserValidationTest class to test validation logic in the User class.
9. Add FilmValidationTest class to test validation logic in the Film class.
10. Introduce DateAfterStandart custom annotation for validating release dates in Film, along with its validator DateAfterStandartValidator.
11. Introduce pom.properties to store project metadata.

Affected: pom.xml, Film, FilmController, NotFoundException, DuplicatedDataException, ValidationException, BaseEntityUtils, User, UserController, UserValidationTest, FilmValidationTest, DateAfterStandart, DateAfterStandartValidator, pom.properties

2024-08-19 01:53 UTC, merged